version: '3.8'

services:
  # Guardian Admin UI
  guardian-admin-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guardian-admin-ui
    restart: unless-stopped
    
    environment:
      # React App Configuration
      NODE_ENV: production
      
      # Guardian Auth Service Configuration
      REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:3002}
      REACT_APP_GUARDIAN_CLIENT_ID: ${GUARDIAN_CLIENT_ID}
      REACT_APP_GUARDIAN_CLIENT_KEY: ${GUARDIAN_CLIENT_KEY}
      
      # Backend URL for proxy server
      BACKEND_URL: ${BACKEND_URL:-http://guardian-auth:8084}
      PROXY_PORT: ${PROXY_PORT:-3002}
      
      # Optional: Proxy Configuration
      REACT_APP_PROXY_URL: ${REACT_APP_PROXY_URL:-http://localhost:3002}
    
    ports:
      - "${UI_PORT:-80}:80"        # Nginx serves React app on port 80
      - "${PROXY_PORT:-3002}:3002" # Node.js proxy server
    
    networks:
      - guardian-network
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    volumes:
      # Optional: Custom Nginx configuration
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ui_logs:/var/log/nginx
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin-ui.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.routers.admin-ui.entrypoints=web"
      - "traefik.http.services.admin-ui.loadbalancer.server.port=80"

networks:
  guardian-network:
    driver: bridge
    name: guardian-network
    external: true

volumes:
  ui_logs:
    name: guardian-ui-logs
    driver: local